blank_issues_enabled: false
contact_links:
  - name: NativePHP Mobile Documentation
    url: https://nativephp.com/docs/mobile
    about: Read the official NativePHP Mobile docs
  - name: NativePHP Community
    url: https://discord.gg/nativephp
    about: Ask questions and get help in the NativePHP Discord
